### ISSUE TITLE
Update color values for each color variable on drought.ca.gov

### ISSUE THREAD

**Issue by adam-little** [cagov/drought.ca.gov#100]
After we have uniformly applied the color variables to all design system components, we need to update the color values for Drought to use the new colors.

Drought color values can be found here: https://www.figma.com/file/3N4dFWhFqiGpWr1DRQoJUM/Design-system-colors?node-id=15%3A1711

This is related to the following Design System issue: [Ensure that all color variables match Figma #117](https://github.com/cagov/design-system/issues/117)

Drought colors:

Primary (#691808)
Primary dark (#4a1106)
Primary light (#965d52)
Primary lighest (#D2BAB5)
Secondary (#313131)
Secondary dark (#222222)
Secondary light (#6f6f6f)
Secondary lightest (#C1C1C1)
Highlight (#FBAD23)
Highlight dark (#b07919)
Highlight light (#fcc665 )
Highlight lightest (#FEE6BD)

**Comment by kkoryaka** [comment]
@adam-little I have updated those variables in staging. Please review: https://staging.drought.ca.gov/

**Comment by adam-little** [comment]
Can you make the following changes:

- Per page feedback container should be Primary **Dark**
- The search bar border and search button should be **Primary**
- The button block buttons should have a border of **Gray 300**
- The borders underneath the "On this page" links should be **Gray 300**

Thanks for your help on this.

**Comment by kkoryaka** [comment]
THis one is done
