### ISSUE TITLE
Add timestamp/date stamp to the site and pages

### ISSUE THREAD

**Issue by abquirarte** [cagov/drought.ca.gov#105]
COVID19 set the best practice of adding a time stamp to the pages to inform users of when content has been updated/refreshed. This element is not yet on the drought site and stakeholder have expressed confusion as to whether the site is up to date. 

Ask- determine best path to include date stamp "last updated" to the drought site (as part of design system).

**Comment by jaredwyee** [comment]
https://github.com/orgs/cagov/projects/7#card-68856070

**Comment by abquirarte** [comment]
Tagging @chachasikes and @kkoryaka for a consult given the overlap with design system. 
cc @xjensen

**Comment by jbum** [comment]
@chachasikes, @kkoryaka -- any developments on this front?  I see that Cannabis also is not showing update dates...

**Comment by chachasikes** [comment]
@xjensen was this ever done? If so - you can close it.
