### ISSUE TITLE
Create and publish Tribal page

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#106]
Per stakeholder request, add a Tribal page to this website and add it to the top menu.

**Comment by thepegisin** [comment]
Initial copy received from Heather Williams 9/13/21.

**Comment by thepegisin** [comment]
Edited for readability and staged 9/14/21.

Draft: https://docs.google.com/document/d/1EwxnpdnbYX9j-5OIUQUPZAd7SJRpqZfflIK9fluu-9Y/edit
Staging: https://staging.drought.ca.gov/tribal-lands/

**Comment by thepegisin** [comment]
Stakeholders are reviewing with other interested parties.

**Comment by thepegisin** [comment]
Got edits from Heather - staged: https://staging.drought.ca.gov/tribal-lands/.

Known issues:
- Needs email for declarations
- Need PDF upload method

cc: @abquirarte

**Comment by abquirarte** [comment]
The email is still blocked. Let me send an email.

**Comment by thepegisin** [comment]
Updated email address on page and re-staged.

**Comment by abquirarte** [comment]
thank you! we can send for final review then publish @thepegisin

**Comment by thepegisin** [comment]
Are you sending, or am I sending, @abquirarte? And if I'm sending, who to?

In the meantime, here's my recommendation for incorporating _Tribal lands_ into the nav without adding another menu item: https://docs.google.com/document/d/1lEm30Siya4DiZ9zma6IcDTXjPiQKUdO_4sktWWbnLMM/edit#

**Comment by abquirarte** [comment]
Go ahead and send to your usual people- original requesters (Heather/Shawn). @thepegisin 

Nav edits approved too! 🙌🏼

**Comment by thepegisin** [comment]
Jared handling approvals. Targeting to publish by Friday.

**Comment by jaredwyee** [comment]
GIven we inadvertently had this on prod, please remove draft outright until we know this should be published (or soon to be). This is on hold / ice until further notice. Thanks

**Comment by thepegisin** [comment]
WP page moved to Trash. Can move back out again when ready to stage/publish.

**Comment by thepegisin** [comment]
Restored page to Staging per email from Heather Williams.

**Comment by thepegisin** [comment]
This request's only sponsor (Heather Williams) has left, and no one else has taken it up. So I'm removing the page from the Staging site, and closing this ticket. If we need to restore it, we can - either from WP's Trash, or make it again from our draft: https://docs.google.com/document/d/1EwxnpdnbYX9j-5OIUQUPZAd7SJRpqZfflIK9fluu-9Y/edit
