### ISSUE TITLE
Drought Content intake and prioritization 

### ISSUE THREAD

**Issue by abquirarte** [cagov/drought.ca.gov#111]
Content [saved here](https://drive.google.com/drive/u/0/folders/1Gwtum7853Ca3rWhb7MSANMJTYRnlFAMe)

- [ ] 1. Tribal lands page edits 
- [x] 2. Weekly drought update 
- [x] 3. Drought assistance update, including:
      a. SWEEP (California Farmers and Ranchers)
      b. Small Community Grants (already on site in drought assistance)
      c. Urban Multi-benefit Drought program (audience: water systems?)

@thepegisin to look over content and propose an information architecture structure. 

AQ to explore: 

- Mailing list (to send out weekly)
- distribution list (for intake)

**Comment by thepegisin** [comment]
Updated staged Tribal page per Heather's email: https://staging.drought.ca.gov/tribal-lands/.

Known issues:
- They need a group email address for tribal drought declarations
- I need to know how to upload a PDF so I can add links to several declarations Heather sent

**Comment by thepegisin** [comment]
Weekly drought updated PDF staging is also waiting for this PDF upload knowledge.

**Comment by thepegisin** [comment]
New content received with 15 more agency programs to add. Updated proposal to accomodate: https://docs.google.com/document/d/1dXhlEOyJ-jGgNeCe4DLdRTm5sWudxHVzILjDYqctfh0/edit#. Working on v2 draft.

**Comment by thepegisin** [comment]
Draft of _Drought assistance v2_: https://docs.google.com/document/d/1dXhlEOyJ-jGgNeCe4DLdRTm5sWudxHVzILjDYqctfh0/edit#

**Comment by thepegisin** [comment]
Draft of _Current drought conditions_ with California Drought Update PDF link added: https://docs.google.com/document/d/1uCwMp7zslvoyDtiJ7mdNK2M_B2bjM0spqim0FyaoziM/edit

Also draft of Update PDF archive: https://docs.google.com/document/d/1kIRIZGLqFHZpaoz1_iZEYC0PeUA7plesyadX3kqXJI0/edit

**Comment by thepegisin** [comment]
Staged changes to _Current drought conditions_ and staged new archive page:
- https://staging.drought.ca.gov/current-drought-conditions/
- https://staging.drought.ca.gov/ca-drought-update-archive/

**Comment by thepegisin** [comment]
Angie approved to publish. Archive page went up fine, but _Current drought conditions_ did not publish. Getting dev help from @xjensen .

**Comment by thepegisin** [comment]
_Weekly drought update_ and _Current drought conditions_ pages are now both published. Need to add _Weekly update_ to nav, but that's not working. @xjensen is working on it.

**Comment by thepegisin** [comment]
Updated _Drought assistance_ is now staged: https://staging.drought.ca.gov/drought-assistance/

**Comment by thepegisin** [comment]
Nav issues are fixed, new nav is up, and link to _Weekly update_ is on it.

**Comment by thepegisin** [comment]
STATUS ROUND-UP:

1. _Tribal lands_ is staged and holding per Heather Williams.
2. _Weekly update_ is published and available from nav. Has latest PDF.
3-5. _Drought assistance_ v2 with multiple programs added is staged and awaiting feedback/approval.

**Comment by thepegisin** [comment]
9/30 ROUND-UP:

1. I let stakeholders know that _Weekly update_ is published, and outlined its accessibility problems.
2. _Drought assistance_ was mistakenly pushed to PROD by Jon. He's rolling it back even as we speak.
3. _Tribal lands_ is staged and not yet approved.

**Comment by thepegisin** [comment]
10/5 ROUND-UP:

1. _Tribal lands_ is staged and holding per Heather Williams.
2. _Weekly update_ is published and available from nav. Has latest PDF (10/4).
3. _Drought assistance_ v2 with multiple programs added is staged and awaiting feedback/approval.

**Comment by thepegisin** [comment]
Staged changes to _Drought assistance_ now published.

**Comment by thepegisin** [comment]
See #106 for completion of _Tribal_ page changes.
