### ISSUE TITLE
Search button gets pinched on mobile

### ISSUE THREAD

**Issue by xjensen** [cagov/drought.ca.gov#115]
On mobile, at narrow-but-still-common screen sizes, the search button gets squished in the header. This results in the icon getting pushed up above the "Search" label. See screenshot.

<img width="414" alt="Screen Shot 2021-09-22 at 15 57 58" src="https://user-images.githubusercontent.com/1208960/134435889-dad584e8-de8b-473c-99d0-dedf7547ed75.png">

@adam-little, what's your opinion on best way to approach this? Apologies in advance if I missed it in Figma.

We'll likely need to address this at the design-system level. But logging it here first.

**Comment by xjensen** [comment]
One thing to add here. To get our ds-branding design system component to work across Cannabis and Drought, I changed the display of these icons on mobile at narrow screen sizes. This affects the way the icons display on Cannabis. For example.

On Cannabis now:
<img width="352" alt="Screen Shot 2021-09-27 at 10 22 18" src="https://user-images.githubusercontent.com/1208960/134956301-af5318c8-98d6-45f2-be1b-5bb74d5dc221.png">

Cannabis before, per Figma designs:
<img width="415" alt="screen_shot_2021-09-27_at_10 06 20_am" src="https://user-images.githubusercontent.com/1208960/134956434-2c228b50-1b29-49a5-81f7-d4f9234c0206.png">

The engineering challenge here is getting things to line up across a lot of different scenarios: Cannabis vs. Drought (where one site has a branding logo and the other doesn't), and desktop vs. mobile.

At any rate, another thing to consider when thinking about these icons. Let me know if any questions. We may want to move this discussion over to design system.

**Comment by xjensen** [comment]
We're fixing this in cagov/design-system#141.

**Comment by adam-little** [comment]
It looks like you found a fix but let me know if you want me to review
anything. I'm just catching up after being offline for the last week.

**Comment by xjensen** [comment]
@adam-little, yes, the original problem here was fixed. I don't know that we still have a problem, but maybe something for your general awareness.

When the screen is mobile but still wide enough, the mobile icons ("Search" and "Menu") will appear inline. This is the same as on Cannabis.

<img width="615" alt="Screen Shot 2021-09-29 at 12 31 44" src="https://user-images.githubusercontent.com/1208960/135336305-89f62e5b-f6e4-4681-9b92-f22eb8f1c012.png">

However, unlike Cannabis, Drought does not have a branding logo. So as soon as the screen is too narrow, the mobile icons will break onto separate lines.

<img width="520" alt="Screen Shot 2021-09-29 at 12 32 04" src="https://user-images.githubusercontent.com/1208960/135336404-d8cac0e1-6770-441a-8060-c3f17ed26013.png">

Seems like the best solution at this time. But if there's a better design for this scenario, we could definitely look into it.
