### ISSUE TITLE
Additions to State actions (homepage and state response page)

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#117]
Add [July 22](http://cert1.mail-west.com/c7rmzEyjmR/anm/mu81zEgtmyuzj/oqn8f6cku/E7n/n0v81zEqvnqz/nq11798/5w7niq?_c=d%7Cze7pzanwmhlzgt%7C18i0a89711da7j5&_ce=1632350461.5d73854a48ce11d329910af4b0095368) and [Sept 23](http://cert1.mail-west.com/c7rmtVyjgI/gtmyuzjanm/81tV/uecijakxaspa/tVe/qvnq/qypa81tV/ecsanw2y9lxb?_c=d%7Cze7pzanwmhlzgt%7C18ncld9l2janfpr&_ce=1632423897.5b7a1acb813aa1665c7563f59c6e84f6) press releases to:
- Homepage under _State actions_
- _State drought response_ page
Requires writing some context text that will need to be checked.

**Comment by thepegisin** [comment]
Drafts ready for @abquirarte's review.

- Homepage (_State actions against drought_): https://docs.google.com/document/d/1q3TjjKsTuZsEfwWEysyFJWj1y9DGGzZGeZdS8ESP_9M/edit#heading=h.hje7vbg7x4a4
- State drought response (_New actions_): https://docs.google.com/document/d/1cp7ujkAzTFpX1_Depm8Fcfrj3ruMItLqt4T39uoRKhg/edit#

**Comment by abquirarte** [comment]
@thepegisin looks great. I approve the content. Good to stage. People to inform of this will be: 

- Heather 
- Erin
- Lisa (I'll send you the emails separately)

**Comment by thepegisin** [comment]
Staged, and all 3 stakeholders were emailed. Note that homepage changes went to PROD.

**Comment by thepegisin** [comment]
Approved and published 9/24.
