### ISSUE TITLE
Change the social share image for Drought

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#119]
When you share the link to a Drought page in Slack or on social media, it shares a hero image. But this image isn't the current hero image on the homepage, it's the last one.

We need:

- The social share image to be the current one (https://drought.ca.gov/media/2021/09/drought-photo.png)
- The ability to update this social share image when we update the hero image, or for it to automagically use the latest hero image

Example (with old image):
![socialshare](https://user-images.githubusercontent.com/63249920/134751515-624ffc8f-8389-41db-bcc0-37b30ca24e4e.png)

**Comment by xjensen** [comment]
@thepegisin It's currently possible to configure these social share images within Wordpress. At the bottom of the Wordpress editor, below the content, you'll find the following panel. The highlighted areas control the social share image.

<img width="1670" alt="Screen Shot 2021-09-30 at 13 40 44 1" src="https://user-images.githubusercontent.com/1208960/135527432-84bbbb8d-e201-484b-9d25-13dec7773728.png">

**Comment by thepegisin** [comment]
Re-opening this so I can remember to update the social share image in all pages but _Drought assistance_.

**Comment by thepegisin** [comment]
Updated social share image to current hero on pages that don't have their own image:

- Homepage
- Current drought conditions
- Newsroom
- Resources
- Tribal lands (to Staging only)
- Urban/Multibenefit Program (to Staging only)
- Weekly drought update

Tested via share on Slack, and correct image now appears.
