### ISSUE TITLE
Numbered lists don't align well with paragraph text

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#120]
Numbered (ordered) lists in body copy on Drought site pages are not aligning with paragraphs, but start a little to the left of them.

We had an example of this on the _Drought assistance_ page, but that list got deleted. You'll have to create an example on a sample page to see it. 

This is not urgent, but should be fixed before we need another numbered list.

**Comment by xjensen** [comment]
Possible fix in cagov/design-system#146.
