### ISSUE TITLE
Track homepage link clicks in analytics

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#125]
We'd like tracking added to homepage links, and results to appear in this report: https://datastudio.google.com/u/0/reporting/50c97641-777f-4f3b-a1d2-62208f294a62/page/jailB

**Comment by jbum** [comment]
I *believe* I've added tracking to all the home-page links (or all the <a> tags at any rate). 

@traintestbritt  If there is a link that is not being tracked, please let me know!  It would help if I could access the GA account so I can confirm, since page-to-page navigation tracking is difficult to debug with  Google Analytics Debugger.

**Comment by britt-allen** [comment]
Hey @thepegisin can you list which links are not currently being tracked? Per @jbum's note I thought all links were being tracked too and the current implementation was dynamic meaning any new link would be auto-tracked. That said, I have no idea what links are not tracked.

**Comment by britt-allen** [comment]
I am so sorry I didn't read this carefully, I thought this was covid and not drought. Please ignore my comment above @thepegisin . @jbum I'll send an email to get you added to the drought GA view and in the meantime i'll dev an analytics plan to capture this data, it'll likely mimic what we're doing for covid

**Comment by jbum** [comment]
I have been added (thanks @britt-allen ) and was able to do a little testing.

I have confirmed that the following things are being tracked:
* Clicks on PDFs. (pdf)
* Clicks on links that go offsite (offsite)
* Clicks on accordions (accordion)
![image](https://user-images.githubusercontent.com/287977/135524713-f423862e-794d-4203-9dfa-58561abb278c.png)

Currently, we are not tracking clicks on other links that navigate in-site (although we do have pageview events when the page-loads, so it seems maybe kind of redundant to track those additional links?). 

@britt-allen let me know if you want those remaining links tracked for clicks (and what code to use: "insite" ?)

**Comment by britt-allen** [comment]
Thanks for confirming Jim. I don't think we need additional tracking. I
think the last piece is for me to surface these analytics on the dashboard
like Peggy requested. I'll aim to have those live by mid week next week!

Best,

Brittany Allen (she/her)
Data Strategist, Insights | CA Office of Digital Innovation
916-270-4718 | ***@***.***
Follow us: web <https://digital.ca.gov/> | blog <https://news.alpha.ca.gov>
| twitter <https://twitter.com/californiaodi>
–––––––––––––––––––––––––
BLACK LIVES MATTER
–––––––––––––––––––––––––

**Comment by britt-allen** [comment]
done! added as a third table to this report: https://datastudio.google.com/reporting/50c97641-777f-4f3b-a1d2-62208f294a62/page/jailB
