### ISSUE TITLE
Drought nav does not update when edited in WP admin

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#126]
@chachasikes showed me how to update the navigation menu in the WP admin (Appearance > Menus). But while the changes I made appear to be saved in WP, they don't appear on the website. This is affecting our ability to link in a new page to the nav.

See Slack thread on this: https://cadotgov.slack.com/archives/C026VJB8Q1G/p1632877211125600

**Comment by aaronhans** [comment]
Drought frontend build is pulling menu structure here https://github.com/cagov/drought.ca.gov/blob/main/src/templates/_data/menus.js#L4

**Comment by abquirarte** [comment]
Per Carter: https://github.com/cagov/drought.ca.gov/blob/main/src/templates/_data/menus.js 
Need new issue on this

**Comment by carterm** [comment]
Issue added...
https://github.com/cagov/wordpress-to-github/issues/50

**Comment by jbum** [comment]
Slack thread --> https://cadotgov.slack.com/archives/C026VJB8Q1G/p1633117513186300

**Comment by xjensen** [comment]
Quick note. Menu work within the wordpress-to-github module has been completed. In short, this set of changes to wordpress-to-github will help trigger site rebuilds whenever a change is made to a menu within Wordpress.

However, deploying this set of changes into live service is on-hold. We're working on putting processes in place around how we deploy wordpress-to-github changes. These processes will help us ensure everyone is properly notified and nothing breaks.

Once the above wordpress-to-github changes are deployed, we'll need to do some minor Drought work here to consume the new menu data. That's the next step, stay tuned.

**Comment by thepegisin** [comment]
Revisiting this. I need to add a new link to the top nav: _Water-saving tips_. Made the change in WP menu, but it's not live. How do we make it live? @xjensen

**Comment by thepegisin** [comment]
Per Jon: "Just takes a few minutes. The menu updates are not pushed out to the site immediately; they need to be pulled when the wordpress-to-github polling service runs every few minutes."
