### ISSUE TITLE
Change URL on "Learn how to save water" homepage button

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#150]
Since the _How you can help_ link came off the nav bar, we need to link that page somewhere else. Request is to change the _Learn how to save water_ link so it goes to https://drought.ca.gov/how-you-can-help/.

This doesn't appear to be under editorial control in WP, but please let me know if it is.

**Comment by jbum** [comment]
Hi @thepegisin -- this is under editorial control, but I edited it (it wasn't obvious to me how to edit it, until I asked Jon) -- you have to select the text and use the link icon.

BEFORE
![image](https://user-images.githubusercontent.com/287977/137007078-4524beeb-aa12-42a0-a323-2ad650e3e0c7.png)

AFTER
![image](https://user-images.githubusercontent.com/287977/137007188-0d2c72f1-5a23-40ba-8cd5-c535f68d2250.png)
