### ISSUE TITLE
Reconnect `chooseTemplate`

### ISSUE THREAD

**Issue by chachasikes** [cagov/drought.ca.gov#161]
drought, main, index.njk was trying to use data.template

This, unforunately, is a wordpress default value that can't be unset in the REST API without breaking monolith. 

Instead, there is `design_system_fields.template` - that's the reliable one from our plugin.
`chooseTemplate` method can go anywhere that makes sense - meta or somewhere.

Looks like in switching over to Posts (and toggling between repo clean up efforts) & cleaning up `manualcontent` the template reverted to use `index.njk` instead of the logic.

Let's sort this out & use it as model for our boilerplate version.
THANK YOU!

**Comment by xjensen** [comment]
This will no longer be needed if we merge #220. That PR uses 11ty's built-in layout features to choose the correct template.
