### ISSUE TITLE
Fix "Read more..." links in news blurbs

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#181]
In _Newsroom_ news blurbs, the copy gets automatically cut off if it runs too long and a "Read more..." link is added. However, that link is going to the wrong place. 

![Readmore](https://user-images.githubusercontent.com/63249920/137971391-9f664e90-2d17-4fcf-946a-c0a2984d0eb5.png)

It should go to the same URL as the title (a press release page or PDF on another website). Instead, it's going to a WP editor page with a Pantheon address. In the example above, that's this: https://live-drought-ca-gov.pantheonsite.io/low-water-levels-trigger-curtailments-for-water-right-holders-in-mill-and-deer-creeks/

Fix so it goes to the same URL as the title.

**Comment by chachasikes** [comment]
Comment left to Peggy in Slack:

Wordpress generates the excerpt. We can try to suppress that default behavior.

A work around might be to copy the body text into excerpt (if you didn’t already).

**Comment by chachasikes** [comment]
Tagging myself on this in case we want to do some WordPress php alteration.

**Comment by thepegisin** [comment]
Trying that excerpt workaround.

**Comment by jaredwyee** [comment]
@thepegisin I thought when we tested this excerpt _did_ work and truncation with read more did not occur.

**Comment by chachasikes** [comment]
This requires (or will be helped by) a WP edit to the default excerpt behavior.

Slating for 1.1.3 release
