### ISSUE TITLE
Test new Content Admin role

### ISSUE THREAD

**Issue by chachasikes** [cagov/drought.ca.gov#183]
@thepegisin  
I created a new role for "Content Admin". It is currently the same as an "Editor" role, except it lets you edit the menu.

I would like to push this to production tomorrow. 

To test this
- [x] Login to the editor test site: https://test-drought-ca-gov.pantheonsite.io/
- [x] See if you can edit the menu. 
- [x] Any changes you make will appear on http://main-test-pantheon.drought.ca.gov.s3-website-us-west-1.amazonaws.com/
- [x] See if there are any WordPress features you need that are missing. (There shouldn’t be.)

- This change will revert you from “Admin” to a new role “Content Admin” and allow me to downgrade you from Admin to Content Admin. It’s not pushed to your production editor yet, I want to validate that this will work for you before we push it live.
- Please let me know if it seems good & I will update the main editor.

If you need a checklist of features, that would be a great QA asset for us to create if you do not already have one. (If you need it, we can make a ticket for that & try that first, then come back to this. Up to you.)

**Comment by thepegisin** [comment]
Did all this, but menu items still don't appear. I think this is being handled in another ticket.
