### ISSUE TITLE
Move Resources content to another page

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#184]
In order to add _Tribal lands_ to the main nav, we must move another link off. _Resources_ is the best choice, per Angie. 

- [ ] Find another place for this content (probably _Drought assistance_ for some and _Current drought conditions_ for others)
- [ ] Draft
- [ ] Stage (when _Tribal lands_ is staged)
- [ ] Publish (when _Tribal lands_ is published)

Note that per @jaredwyee, we could temporarily leave _Resources_ in place on the homepage, even after adding _Tribal lands_.

**Comment by jaredwyee** [comment]
DWR going to do a once over on the "More resources" section of Resources page as the list is quite lengthy. Also we pointed out the CalOES link for water assistance should possibly be removed as it isn't a helpful link

**Comment by thepegisin** [comment]
Did not end up doing this and it's no longer mentioned, so closing this ticket.
