### ISSUE TITLE
WordPress API sorting broken

### ISSUE THREAD

**Issue by carterm** [cagov/drought.ca.gov#190]
Using the WordPress API with the "orderby" parameter should sort.  Customizations to the sorting algorithm appear to have broken it.  This makes publishing impossible until the sorting algorithm is restored because there is no way to get the most recent modified date.

These results should be sorted by modified desc...
https://live-drought-ca-gov.pantheonsite.io/wp-json/wp/v2/posts?per_page=10&orderby=modified&order=desc&_fields=slug,modified

**Comment by jbum** [comment]
Woot!
