### ISSUE TITLE
Guide on how to post news item for training stakeholders

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#197]
As discussed, draft guide of steps and screenshots of how to post news items on Drought site. Outcome will be to use in training stakeholders and as future reference for them.

**Comment by thepegisin** [comment]
- [ ] Draft steps with screenshots in Google Docs
- [ ] Have @chachasikes check for accuracy
- [ ] Get approval/edits from @jaredwyee 
- [ ] Share with stakeholders when training

**Comment by thepegisin** [comment]
Draft: https://docs.google.com/document/d/1SXHOx0npr6FwUXG12ubmLff04kVmTPp7WckT8V_wOw8/edit#

**Comment by jaredwyee** [comment]
Thanks @thepegisin Looks great. Just going to hold for a bit on scheduling the initial training session to make sure we don't throw too much at stakeholders at once.

**Comment by jaredwyee** [comment]
Guide is done. Doing initial training session today.

**Comment by jaredwyee** [comment]
While we have some rockiness with receiving emails for invites and OTP, stakeholder was able to setup 2fa via authenticator app and has first new posted up successfully.

**Comment by thepegisin** [comment]
Made into slides and shared with trainees. https://docs.google.com/presentation/d/1_v2Yi2O07bu2ay_8tzaL1TS1R0VDR6fW8lIQ-DWTd1Y/edit#slide=id.gd01156d741_1_3
