### ISSUE TITLE
Twitter social feed display method/plugin

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#203]
In order to better aggregate and highlight what drought taskforce agencies/departments are communicating via social, we want to include a feed on the drought site. This is to bring together content being put out from the most active "channel" and liven up the drought site so it's not as static.

If we have to start with one handle it would probably be CA DWR's (https://twitter.com/CA_DWR) for now. Potential concern of not elevating cross agency/department taskforce entities however.

- Focus on possible technical implementation initially. Customized CSS considerations will be considered after we see the "prototype" implementation that might work for our stakeholders
- Can multiple handles be followed in a feed? (otherwise start with CA_DWR)
- May need to consider container height to give a better "feed" experience. On Cannabis it feels like we emphasis one major tweet and then the "scroll through the feed" experience feels a bit muddled (sometimes looks like an iframe in an iframe).
- Need to consider where we would place the feed. Would it replace State actions or News? Show below? Potential placement of a "overall water level" chart as well, so the drought site could expand into 4 "rows" vs 3 today.

**Comment by jaredwyee** [comment]
@xjensen amongst the three main options on https://publish.twitter.com/# the timeline is probably the best balance of show all the activity in an easy "view port".

Twitter mention you can show case lists... so maybe that's the route to group feeds across handles.

**Comment by xjensen** [comment]
Good call. This timeline feed for your list gives us the same output/embed code as what's used on Cannabis. The approach seems very doable. 

I'll test it out in Drought and report back.

**Comment by xjensen** [comment]
@jaredwyee Here's a first pass.

<img width="1418" alt="Screen Shot 2021-11-04 at 13 52 44" src="https://user-images.githubusercontent.com/1208960/140418353-9f725edc-4c02-429c-8f41-e44f949870e3.png">

Notes.

* This is pretty straight-forward. The timeline/publish stuff on Twitter takes care of the hard work of combining the feeds.
* Styling options are limited. We can't do much to re-style the content within the widget.
* That said, I have removed the borders and footer on the widget here, compared to Cannabis. Also improved behavior of the scrollbar.
* We can also remove the header ("Drought, A Twitter list by..."). But there are Twitter TOS requirements that we give attribution for the feed. So we'd need to recreate it, but could do so using our own styling and sensibilities.

> ...sites must add their own Twitter attribution, link to the source timeline, and comply with other Twitter [display requirements](https://developer.twitter.com/en/developer-terms/display-requirements).

**Comment by abquirarte** [comment]
Doing a **courtesy FYI** to @adam-little, @wrendo  @chachasikes and @aaronhans.

**Comment by xjensen** [comment]
@aaronhans Intersection Observer is a great idea here. Depending upon opinions regarding styling, I'm wondering if we should develop this as a new component in the Design System. ds-twitter-feed.

**Comment by jaredwyee** [comment]
awesome @xjensen thanks for looking into this. I will defer to @adam-little on how much we might want to customize/control the styling. My weighing is I think we can start with what's more out of the box first to move faster to getting stakeholder feedback and potentially putting into prod

**Comment by zakiya** [comment]
I can say from experience that the Twitter API changes often and they make it pretty difficult to make style changes without some serious hackery. I would also keep an eye on the terms of service. At one point it specifically mentioned government use but I don't see that in the current developer agreement.

**Comment by aaronhans** [comment]
Good plan to make this a component @xjensen 

Will be great to share improvements as they are made

**Comment by adam-little** [comment]
I'm fine with taking the same approach to Cannabis. My only request is that we add a 1px #E1E0E3 border with a 5px corner radius to the container. 

See screenshot from [Figma](https://www.figma.com/file/veQuKQHf8gK5JdFEoMLGRD/Design-system-UI-kit?node-id=3%3A2392) below.

Note that this border does not appear on headless but it's one of the items I flagged in the design QA document. So if you could add it there as well, that would be great.

![image](https://user-images.githubusercontent.com/69167298/140560508-d61b757c-f689-489d-a5f9-20e00c466002.png)

**Comment by jaredwyee** [comment]
@xjensen are we at the point where it is reasonable for me to ask for a Twitter "list" URL from a CA drought taskforce Twitter handle? So that we don't use my personal one :).

Next step would be show a staged version with the real feed/list to get input.

**Comment by xjensen** [comment]
Adding updates from Slack into this comment, for posterity.

* We have a new [mock homepage](https://staging.drought.ca.gov/sandbox-landing/), in staging, where we can test Twitter feeds.
* Every Twitter thing you see on that mock page is achieved via Wordpress alone, with no additional development.
* The Twitter feed widget already defers its loading via `<script async>`. That seems to be working.
* Added the border requested by Adam via inline class in Wordpress, for now. Maybe we could make a simple utility class for adding bordered boxes to things, and add it to ds-base-css.

At this point, creating a separate component in the Design System doesn't feel like a priority. Good for later, but not necessary for now. Twitter's exported code, plus just one CSS class (to add the border), does pretty much everything we need. This is open to opinion though; let's see how this develops, and let me know if I should go forward with the DS component approach.

**Comment by aaronhans** [comment]
Nice work @xjensen I'd vote for creating a design system component whenever we can fit it in because this element causes both performance and accessibility violations so is the prime candidate to improve those aspects on all the sites it is used.

Once it is a component we could start making small improvements like loading via intersection observer which would make a big improvement on mobile in the cannabis and drought layouts.

Eventually we could swap it out with a version that didn't have so much client side javascript by interacting with the twitter api ourselves.

**Comment by xjensen** [comment]
@jaredwyee Is there still any desire to use a Twitter feed on Drought's homepage? I'm wondering if we should close this issue.

**Comment by jaredwyee** [comment]
Thanks @xjensen I can close and resurrect if needed.
