### ISSUE TITLE
Mobile view - menu & search button location

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#209]
Consider better left alignment. Possible clash with DS pattern due to lack of a logo.

![image](https://user-images.githubusercontent.com/85529382/141172677-c17421e0-b543-4bcb-85a0-f44b7baec925.png)
![image](https://user-images.githubusercontent.com/85529382/141172691-3cea6b29-8a6e-4966-acd0-a8064531e046.png)

**Comment by xjensen** [comment]
Fix in progress at #212.
