### ISSUE TITLE
Remove "external link" icon when "PDF" icon is also present

### ISSUE THREAD

**Issue by adam-little** [cagov/drought.ca.gov#221]
Currently, a link to a PDF on an external website will result in two icons [see screenshot].

![image](https://user-images.githubusercontent.com/69167298/143934863-d838bdfb-5456-42e3-afe5-a2aaa018c78e.png)

I recommend that the PDF icon "trumps" the external link icon. Therefore, if there is an external link to a PDF, the link will only display the PDF icon.

Reasons:

- Reduce visual clutter
- If browser behavior is to save PDF to downloads, then the user will not find themselves navigating away from the current page. The external link icon is meaningless.
- If browser behavior is to open the PDF in the browser, then user will find themselves leaving the current website experience regardless of where PDF is hosted. The external link icon is redundant. 

This is true for all design system websites.

**Comment by adam-little** [comment]
Assigning to @jaredwyee for triage

**Comment by xjensen** [comment]
We may need to combine our pdf-icon and external-link-icon Design System components to achieve this.

@aaronhans @kkoryaka What do you think about having one Design System component to handle all link decorations?

**Comment by jaredwyee** [comment]
Thanks @xjensen . If it gets unnecessarily complex, this isn't a high priority by any means!

**Comment by kkoryaka** [comment]
@xjensen we need to switch javaScript order, and it will fix this issue. (We have css in external link component that disables external link if pdf is present, but  pdf JavaScript needs to go after external link because unfortunately there is no CSS Previous sibling selectors.), I will create PR to fix it.
![Screen Shot 2021-11-30 at 11 41 04 AM](https://user-images.githubusercontent.com/31669748/144117482-cb6ebd45-5fa1-4f8c-a95e-f6b0e295c147.png)

**Comment by kkoryaka** [comment]
BTW, in staging it works correctly: https://staging.drought.ca.gov/newsroom/

**Comment by xjensen** [comment]
@kkoryaka Clever, I like it.

I think it will be challenging to support this kind of instruction when we start inviting outside teams to use the Design System. But It definitely works for us.

**Comment by kkoryaka** [comment]
@xjensen I agree, I would hate these extra instructions to avoid issues like this. So combining these two components into one would take care of it.

**Comment by kkoryaka** [comment]
@xjensen created this issue: https://github.com/cagov/design-system/issues/225 in design system to combine those two components into one ds-link-icon
