### ISSUE TITLE
Drought Tracking Data Investigation

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#229]
**Major Reservoir Data**
- For [major reservoirs ](https://cdec.water.ca.gov/resapp/RescondMain) showcase the current capacity, relative to average capacity and total capacity
- Thus we need, list of reservoirs (they have a code eg CLE, SHA), current capacity, average capacity, total capacity. This data should be available daily
- https://cdec.water.ca.gov/dynamicapp/wsSensorData
- https://cdec.water.ca.gov/resapp/service/res/conditions

**Snowpack**
- JSON: shows snow water content at bottom https://cdec.water.ca.gov/snowapp/services/statewide/swe 
- https://cdec.water.ca.gov/reportapp/javareports?name=DLYSWEQ
- We want to show snowpack relative to April 1 year avg %
- https://cdec.water.ca.gov/snowapp/sweq.action map visual

**Conservation Data** - will likely have manually update
![image](https://user-images.githubusercontent.com/85529382/144674125-982044ad-c3f2-45f5-9203-f93b7814d26e.png)
- [Excel: June 2014 - September 2021 Urban Water Supplier Monthly Reports](https://www.waterboards.ca.gov/water_issues/programs/conservation_portal/docs/2021_reports/uw-supplier-data111621.xlsx)
- I can't reconcile perfectly the Sept change data from the Excel sheet
![image](https://user-images.githubusercontent.com/85529382/144674877-477699d7-1b39-41e8-a07d-c7a2b33cc64c.png)
![image](https://user-images.githubusercontent.com/85529382/144674908-1c8464a3-6a3b-4dc3-bfcb-a3d56699da6e.png)

### MAYBE USE

**Drought Monitor Map & Severity Levels**

- Ability to pull CA specific drought monitor map as it updates
- Ability to pull respective drought severity level % (D0 through D5) in conjunction with map - meaning align current date/week to that of the map.
- https://droughtmonitor.unl.edu/DmData/DataDownload/WebServiceInfo.aspx#comp
- example: `https://usdmdataservices.unl.edu/api/StateStatistics/GetDroughtSeverityStatisticsByAreaPercent?aoi=06&startdate=1/5/2021&enddate=1/11/2021&statisticsType=1`

### NOT PROCEEDING WITH BELOW

**Groundwater Monitor - Wells at normal level**
DWR recently launched https://sgma.water.ca.gov/CalGWLive/
It's admittedly pretty overwhelming to look at the arcGIS map. The clearest data vis to share looks to be the wells (% proportion) at below, normal, or above usual levels. Adam has mocked this where we depict 75% of wells are below their respective regular normal level. 

Not clear yet how we can get this data in a structured manner, but if it's 3 numbers maybe we can scrap the page.
- https://data.cnra.ca.gov/dataset/periodic-groundwater-level-measurements
- I couldn't reconcile the % of wells under normal (74%), normal, above normal per the dashboard vs the ArcGIS histogram
![image](https://user-images.githubusercontent.com/85529382/144680992-af504183-186e-444b-9b64-0414e28e35d0.png)
![image](https://user-images.githubusercontent.com/85529382/144681018-51ca1264-9f0e-4527-97a1-b21bde433b15.png)
![image](https://user-images.githubusercontent.com/85529382/144681031-e56fd6e5-ea57-44f2-a028-15819a7eb22f.png)

**Comment by xjensen** [comment]
Re: Groundwater levels, it looks like the following _might_ be what we need. But it's listed as still under development.

https://data.cnra.ca.gov/dataset/calgw_live/resource/960d0135-eae0-451a-8d9b-f0d4eef9c6c7

**Comment by xjensen** [comment]
I've been working on a way to clip California out of the Drought Map using GIS data. Not totally finished yet, but feeling good about being able to do this.

<img width="569" alt="Screen Shot 2021-12-01 at 16 04 48" src="https://user-images.githubusercontent.com/1208960/144473633-586a5fff-f371-46d9-b558-41633c671ccd.png">

**Comment by jaredwyee** [comment]
@xjensen cool! I like the cleaner display of the state without county lines (potentially noise). Would we be able to adapt the US map fetch process for CA specifically?

The Drought monitor site has the images readily available for each update the same way as far as I know.
https://droughtmonitor.unl.edu/data/png/20211130/20211130_ca_none.png
https://droughtmonitor.unl.edu/CurrentMap/StateDroughtMonitor.aspx?CA

Stakeholders may want the county and/or bodies of water and rivers indicated.

**Comment by jaredwyee** [comment]
I'll repeat, cooool! Great to know. Let's listen to what stakeholders think. In our back pocket, we'll know we have the more sophisticated avenues should we want to keep building on top of the map notion.

**Comment by jaredwyee** [comment]
Per Jon, makes more sense to know what the intended visual is for major reservoir levels before building out. Pulling down the data is fairly simple line a code so not a real benefit to chunk apart the work.

**Comment by jaredwyee** [comment]
@xjensen i added the links for snowpack in the initial comment of the issue. As we've discussing 1) reservoirs and 2) snowpack should be the focus for understanding feasibility of data flow to drive chart/data on site.

We are still pending access to data and better understanding for precipitation and temperature.
