### ISSUE TITLE
Image comparison slider - explore feasibility

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#231]
Update: 

Refer to design in latest mock: https://www.figma.com/file/VdQOfgIJpYD90onzb7PJSZ/Drought.ca.gov-screens?node-id=361%3A14792

Cropped images are in Figma here: https://www.figma.com/file/VdQOfgIJpYD90onzb7PJSZ/Drought.ca.gov-screens?node-id=347%3A7467

Source images are here:

Oroville 2016: https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000aHWl0wNQpUk/I0000GajzUSfb1ek/KG-oroville-aerials-45653-jpg
Oroville 2021: https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000O2Iqw1M4mSE/I0000VROqi4LzN68/2021-07-26-KG-9979-Oroville-drone-jpg

**Additional requirement**
Be able to swap current hero to slider, and back to hero as needed. At a later point in time we may want to emphasize a different message and would place the slider elsewhere or remove it as needed

----

**Goal:**
On the Drought site we want to visually and emotionally convey the stark contrast of conditions, contrasting different years. 

One idea is to do a sliding image viewer where you have two images, initially split in half. You can slide to reveal all of image one or slide to reveal all of image two. The benefit to the user is to be able to compare two landscapes/reservoirs from different years but similar orientation/perspective in the photograph.

The goal of this ticket is explore how this might be done on the front end and determine how easy-difficult it may be. This is **not** a final design spec to make build the front end component.

<img width="1696" alt="Tracking Drought" src="https://user-images.githubusercontent.com/85529382/144509125-7fc1b83f-62b1-4688-8b12-70a9989b0aab.png">

Possible image sets. Likely need some cropping

**Set 1:**
https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000O2Iqw1M4mSE/I0000VROqi4LzN68/2021-07-26-KG-9979-Oroville-drone-jpg
https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000aHWl0wNQpUk/I0000GajzUSfb1ek/KG-oroville-aerials-45653-jpg

**Set 2:**
https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000O2Iqw1M4mSE/I0000DSysWwXgAdY/2021-07-26-KG-9994-Oroville-drone-jpg
https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000pBIlrzqSMu0/I00001bfJ.gWE.oU/Oroville-Full-PJH-07-20-11-0154-jpg

**Set 3:**
https://pixel-ca-dwr.photoshelter.com/galleries/C0000JjnSV3JF_oI/G0000TM7bNnJ4f.A/I0000xCVkHoBXjS0/2021-07-20-KG-9793-Oroville-drone-jpg
https://pixel-ca-dwr.photoshelter.com/galleries/C0000JjnSV3JF_oI/G0000uEn2rCSLBcA/I0000xsciFunaVEo/Oroville-Full-PJH-07-20-11-0182-jpg

**Comment by jaredwyee** [comment]
@adam-little  FYI, memorializing possible sets of images I noted in Slack

**Comment by xjensen** [comment]
Here's some prototype work on image sliders. Not production-ready, of course, but I think this shows it's doable.

https://image-comparison-slider.pr.drought.ca.gov/pr/image-comparison-slider/sandbox-1/

**Comment by jaredwyee** [comment]
👍🏼 looks great. Thanks for protyping feasibility.

**Comment by jaredwyee** [comment]
@adam-little give spec-ed slider design to Jon when you can with cropped example images. We may get new images from stakeholders as well.

**Comment by adam-little** [comment]
@xjensen Here are some images you can experiment with:
![Oroville Combined](https://user-images.githubusercontent.com/69167298/146256046-08a2de9c-bfea-4ac4-bd31-dc303d86ddcc.png)
![Oroville 2016](https://user-images.githubusercontent.com/69167298/146256048-74114930-def9-440f-b44b-ef7e8f51b718.png)
![Oroville 2021](https://user-images.githubusercontent.com/69167298/146256049-a42d211d-6c74-42a4-ba26-0f918ce1b9e1.png)

Cropped images are in Figma here: https://www.figma.com/file/VdQOfgIJpYD90onzb7PJSZ/Drought.ca.gov-screens?node-id=347%3A7467

Source images are here:

- Oroville 2016: https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000aHWl0wNQpUk/I0000GajzUSfb1ek/KG-oroville-aerials-45653-jpg
- Oroville 2021: https://pixel-ca-dwr.photoshelter.com/galleries/C0000jk3Mpvy07_U/G0000O2Iqw1M4mSE/I0000VROqi4LzN68/2021-07-26-KG-9979-Oroville-drone-jpg

**Comment by jaredwyee** [comment]
@xjensen @adam-little are you both cool with me sending the visuals to stakeholders to keep them in the loop of our progress?

**Comment by adam-little** [comment]
I don't see any problem with that

**Comment by jaredwyee** [comment]
@adam-little  @xjensen a clarification the dates are actually

- May 11, 2016 (Full looking Lake Oroville)
- July 26, 2021 (empty looking Lake Oroville)

**Comment by jaredwyee** [comment]
Essentially vetted for feasibility. However, not incorporating into the homepage redesign so moving to DONE for now (long over due)
