### ISSUE TITLE
Edits to Current drought conditions page

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#238]
Jared suggested text to update the _2021 overview_ section of the **Current drought conditions** page.

- [x] Work his suggested text into the whole: [draft](https://docs.google.com/document/d/1uCwMp7zslvoyDtiJ7mdNK2M_B2bjM0spqim0FyaoziM/edit#heading=h.o04u1kmcg712)
- [x] Notify @jaredwyee so he can get stakeholder buy-in/edits
- [ ] Get approval or edits
- [ ] Stage
- [ ] Publish

**Comment by xjensen** [comment]
@thepegisin Okay to close this?
