### ISSUE TITLE
Certain PDF links 404. On prod the URL points to drought.ca.gov when the link should go elsewhere.

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#250]
On https://drought.ca.gov/state-drought-response/ I noticed some of the PDF links incorrectly point to URLs with drought.ca.gov/media as the path. These links are suppose to point elsewhere. The result is 404.

**WRONG LINK:** https://drought.ca.gov/media/2021/07/7.8.21-Conservation-EO-N-10-21.pdf 
**CORRECT LINK:** https://www.gov.ca.gov/wp-content/uploads/2021/07/7.8.21-Conservation-EO-N-10-21.pdf

![image](https://user-images.githubusercontent.com/85529382/149036249-a6c1625f-db16-4096-a8f1-cc458119ac99.png)

The strange thing is in CMS edit mode for the page, the links look as intended!

![image](https://user-images.githubusercontent.com/85529382/149036376-b1fffe4e-d096-4194-ac4b-6b0e5d556545.png)

**Present behavior:** production PDF link is not as saved in CMS page

**Expected behavior:** production PDF link should be the same as saved in CMS

**Comment by xjensen** [comment]
Looks like those three links are the main extent of the damage. 

The problem also appears on two rendered post pages. I'd be surprised if these pages receive any traffic.

https://drought.ca.gov/emergency-proclamation/
https://drought.ca.gov/reduce-water-use/
