### ISSUE TITLE
Make text and padding on Production and Staging be identical

### ISSUE THREAD

**Issue by thepegisin** [cagov/drought.ca.gov#264]
I noticed when staging a hero text change on the homepage that there is a difference between how the text looks on Staging (smaller) and how it looks on Production (bigger). The font size seems the same, but on Production, it takes up more space. 

This is a concern because we need Staging to give us the real look we should expect before we publish.

Examples:
STAGING
![staging](https://user-images.githubusercontent.com/63249920/152440125-cfc1078c-a1bf-47d6-af21-44ff2a7f706d.png)

PRODUCTION
![production](https://user-images.githubusercontent.com/63249920/152440175-2c1aff5e-e390-43df-a32a-f5c283bda485.png)

**Comment by thepegisin** [comment]
BTW, yes, in these examples this is too much text in the hero space - but I included them because they illustrate the problem well.

**Comment by xjensen** [comment]
I fixed this as part of the recent redesign work. Closing. Can reopen if needed.
