### ISSUE TITLE
Update footer link with 'CA water watch'

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#267]
I don't believe I can do this easily as an editor in WP. I didn't see the Appearance>Customize menu Aaron suggested.

**Requirements:**
- Remove 'My dry water supply' link in footer
- Replace with 'CA water watch' which points to https://cww.water.ca.gov/

**Comment by jaredwyee** [comment]
@xjensen  Bump. can you update this foot link?

**Comment by xjensen** [comment]
@jaredwyee Apologies for missing this. It's done.

This change is possible via Wordpress; it's somewhat hard to find within the Appearance => Menus interface (in the "Content Menu"). I went ahead and made the change this time to ensure it's working. Happy to provide further guidance, just let me know.
