### ISSUE TITLE
Major Reservoir Data Visual

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#268]
![image](https://user-images.githubusercontent.com/85529382/156047442-512f0e82-5940-4bdb-a46b-8da3a72fcffa.png)

**User/job story**: 
When I am interested in learning about our water storage situation, 
I want to obtain high-level and simple information about our reservoirs, 
so I can be [concerned/relieved] about our human-made water storage.

**Background**: One of the data elements we want to show is major reservoir level relative to the average. 

To do so, we need need to obtain the daily reservoir level for each major reservoir and its average. We then sum the levels across the major reservoirs and sum the averages. Then we take the sum of present levels and divide by the sum of average levels to calculate the delta from average.

This data should update daily from CDEC updates. Refer to prior investigation of where to access data: https://github.com/cagov/drought.ca.gov/issues/229

When considering how to implement, err on minimal effort to maintain and high robustness as a "feasibility" consideration. Consider how to build in soft fail overs (eg if data doesn't update, it uses last known good data) vs screwing up the entire data visual display). Or there isn't data for all major reservoirs? No value in the JSON might be -9999 (or blank).

**Design:** [Figma Mock](https://www.figma.com/file/VdQOfgIJpYD90onzb7PJSZ/Drought.ca.gov-screens?node-id=553%3A10063)

* The gray bar is the total capacity of major reservoirs
* The blue bar is the current level of major reservoirs
* The dotted line is the average of major reservoirs
* the red XX% is % of average levels
* Hover on the gray bar should show tooltip with total capacity in thousand acre-ft (TAF)
* Hover on the blue bar should show tooltip with current level in thousand acre-ft (TAF)
* Hover on the dotted line should show tooltip with average capacity in thousand acre-ft (TAF)
* Learn more link should go to https://cdec.water.ca.gov/resapp/RescondMain
![image](https://user-images.githubusercontent.com/85529382/154764238-83142d47-0486-489a-9f4d-9e8f1817b9db.png)

![image](https://user-images.githubusercontent.com/85529382/154764212-1275c0bf-8523-4bf0-8a1e-935789ced9ae.png)

![image](https://user-images.githubusercontent.com/85529382/154764256-81ea49ed-f8a9-451a-a231-9175863ca8f7.png)

**Additional Requirements:**
* Text elements should be able to be updated by content editors (eg subtitle and header)
* Chart should update daily based on latest information available from CDEC
* Consider a last known successful update date should troubleshooting be needed by a developer (not visible to website visitors)
* Placement of the chart should be modular (doesn't have to be changed by content editor, just a factor should we want to reorganize the layout). Similarly, we should be able to embed this chart on other pages of the drought.ca.gov site.

**Data Source**
https://cdec.water.ca.gov/resapp/service/res/conditions?date=2022-02-15&stationIds=SHA

Query with input date and station ID(s). If you put in a future date, it returns back the last date in which there is data.

Returns back info of interest:
* storage
* avg
* cap

The numbers are in acre-feet so we would want to simplify it by dividing by 1,000 to arrive at thousand acre-feet (TAF).

Example output: 
`[{
    "stationId": "SHA",
    "disabled": false,
    "detailed": true,
    "tags": "1_154 res Daily Report",
    "reservoirName": "Lake Shasta",
    "drinkingWater": false,
    "stationName": "SHASTA DAM  (USBR)",
    "latitude": 40.718,
    "longitude": -122.42,
    "elevation": 1067,
    "valDate": "2022-02-17 00:00:00.0",
    "actDate": "2022-02-17",
    "day": 17,
    "month": 2,
    "storage": 1681973,
    "avg": 3143357,
    "cap": 4552000,
    "pctAvg": 53.51,
    "pctCap": 36.95
}]`

**Major Reservoir station codes**
* SHA
* ORO
* BUL
* FOL
* CMN
* CLE
* WRS
* SNL
* CCH
* CSI
* CAS
* DMV
* NML
* DNP
* EXC
* MIL
* PNF

**Comment by jaredwyee** [comment]
Let's review next week

**Comment by xjensen** [comment]
@jaredwyee My one concern here is about how to handle the various on-hover interactions on mobile, since hovers can be clunky on phones. Do we still need to display that more detailed info on touchscreens, and if so, would the design look different?

**Comment by jaredwyee** [comment]
@adam-little @kmbrlygl thoughts on how to handle for mobile?

Big picture, I do not think the hover-over details are critical information. They are useful "supporting" pieces of data that underscore the validity of the chart (through the precision of using real numbers and allowing someone to vet our math).

But if you had no clue about acre-feet capacity of our reservoirs, it would be totally arbitrary to the lay person.

**Comment by jaredwyee** [comment]
Looking at covid charts with data notes for reference, the "hover" data note on the chart reveals if you tap on a part of a line. Given this drought data viz is not a line and is a basic bar, I think it's sufficient to show the data note upon tap and then revert to default state when you tap in negative space to the data note.

Assuming responsive resizing occurs there might not be any special handling needed for mobile. But would want to see an example before deciding that completely. Still, not a critical priority as I commented above given it's nice to have info.

**Comment by jaredwyee** [comment]
From our convo with stakeholders, we will simply state the % of average vs relative comparison of above/below average.

**Comment by xjensen** [comment]
Currently working through this on branch `268-prototype-reservoir-levels`. I've followed the latest mocks in Figma. Always open to changing it as needed.

<img width="571" alt="Screen Shot 2022-03-07 at 16 56 27" src="https://user-images.githubusercontent.com/1208960/157144418-1200c2f2-b0b2-4e3d-8db6-bf7d1ef7234c.png">

**Comment by jaredwyee** [comment]
Looking good!
