### ISSUE TITLE
Statewide GA Tag

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#67]
we need to add this tag in addition to the drought-specific account in order to pull drought data into the U/X research hub. 

Statewide code: 
            //statewide GA property
                gtag('config', 'UA-3419582-2');

**Comment by jaredwyee** [comment]
@jbum  this was completed, correct?

**Comment by jbum** [comment]
Yes. marking this done.

**Comment by jaredwyee** [comment]
Marking closed.
