### ISSUE TITLE
Reconcile "How you can help" and the Tips page

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#76]
Our main call to action is to view the water saving tips, which has been updated to emphasize outdoor reduction.

The **How you can help** page lists 3 example tips but they are not our top water saving tips. This is mainly due to drafting/expanding on the tips after the **how you can help** was drafted :).

Reconcile the content between the two for consistency. Over time we may expand the **How you can help** page to include how to report water waste
https://drought.ca.gov/how-you-can-help/
https://drought.ca.gov/water-saving-tips/

**Comment by jaredwyee** [comment]
@thepegisin in light of the user testing, I think these two pages should be unified. Then it can serve as the drought site's tips/how to conserve page while we keep evaluating where the best content exists (maybe pointing to SaveOurWater as a secondary action on our water saving tips page).

**Comment by thepegisin** [comment]
Tasks:

- [ ] Draft merged page: https://docs.google.com/document/d/1F7qPNFSi_2BeAXSRhAYWxKt_-1vjqDmHU0Wy5AzKWUw/edit#
- [ ] Get approval through @jaredwyee Stage
- [ ]  Check
- [ ] Publish
- [ ] Add Water saving tips to navigation

**Comment by thepegisin** [comment]
Was not able to add to navigation. Will comment on existing ticket for this: #126
