### ISSUE TITLE
Add ethnio javascript to site

### ISSUE THREAD

**Issue by jaredwyee** [cagov/drought.ca.gov#85]
we want to be able to do Ethnio intercept surveys to get feedback and potentially recruit visitors on drought.ca.gov. In order to do that we need the below JS added
```
<!-- Ethnio Activation Code -->
<script type="text/javascript" language="javascript" src="//ethn.io/35244.js" async="true" charset="utf-8"></script>
```

https://help.ethn.io/hc/en-us/articles/200202455-Placing-Ethnio-Javascript-The-Details

**Comment by jaredwyee** [comment]
@jbum  please pick up when you are able, thanks

**Comment by jbum** [comment]
Just noticed this.  It'll probably take me a few days to adjusting to noticing these issues, since they only go to my email (unlike Jira). I get so much email from Github that I auto-archive it all. I'll have to work on refining my filters to surface these ones.

**Comment by jbum** [comment]
Suggestion: use three back-ticks around code samples.

**Comment by jbum** [comment]
Code has been added.  Keeping issue open. Next week I want to incorporate this into the Wordpress template.

**Comment by jaredwyee** [comment]
Thanks! @clarita1980 FYI the ethnio code should be on the drought site now.

**Comment by clarita1980** [comment]
Yes, I tested on Friday.

**Comment by jbum** [comment]
Closing for now. Ethnio was removed a couple weeks ago by Aaron with Jared/Clara's permission.
