### ISSUE TITLE
Fix design of drought map

### ISSUE THREAD

**Issue by adam-little** [cagov/drought.ca.gov#96]
Currently, the grey border only surrounds the map graphic.

The desired design is for the grey border to surround entire visualization, including the key. 

The container that the grey border surrounds should fill the entire column width.

Desired design in [Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=2872%3A9768):
![image](https://user-images.githubusercontent.com/69167298/127929261-05c0a65a-2aee-49a4-a41f-2470b4acd8a6.png)

Current design: 
![image](https://user-images.githubusercontent.com/69167298/127929049-26eca055-0121-40db-a074-b15d800a9887.png)

**Comment by jaredwyee** [comment]
Thanks Adam. Assigning to Jim as workable but not urgent.

**Comment by adam-little** [comment]
Thanks @jbum !

**Comment by jaredwyee** [comment]
Marking closed and moving to done
