### ISSUE TITLE
drought: use all components in design system

### ISSUE THREAD

**Issue by aaronhans** [cagov/drought.ca.gov#98]
The drought site still has many components whose code is hardcoded in the repo

We recently went through this exercise with headless cannabis where we deleted all the hardcoded components, installed and used the versions from the design system. 

When we added all of these components to the design system we reviewed all the code in both drought and cannabis and made sure all updates were included so theoretically this should go smoothly

**Comment by aaronhans** [comment]
Thanks for starting on this work @xjensen! 

Feel free to rescope this ticket to whatever size you feel is reasonable, we can create follow up tickets to finish this work

**Comment by xjensen** [comment]
I hit a snag when implementing the ds-branding component. See cagov/design-system#115. Stay tuned.

**Comment by xjensen** [comment]
We're now also pending the following design-system requests.

cagov/design-system#119
cagov/design-system#120
cagov/design-system#121

**Comment by chachasikes** [comment]
Good to see this, I'll keep an eye out for other hardcoded problems.
